name: CI

on: [push]

jobs:
  OSX:

    runs-on: macOS-10.14

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    
    - name: Install Dependencies
      run: |
        brew install llvm
    
    - name: Build and test
      run: |
        export PATH=$(brew --prefix llvm)/bin:$PATH
        export CC=clang
        export CXX=clang++
        ./codebuild/common-posix.sh
